language: ruby
rvm:
- 2.6.0
before_install:
- gem update --system
- gem install bundler
before_script:
- gem install html-proofer
- git clone https://github.com/Remillardj/jremillard.git
- cd jremillard/
script:
- bundle install
- bundle exec jekyll build
deploy:
  provider: firebase
  global:
    token: "QuEv7PvCX/WPlphrHK5p3PnjTsE5Rl3piSN/+zaWYodIddsdg58qfEu371RCLmUde9RwdPqJ/3t+GYQeXLiuGE/8xuczQ898Tb9ZSgaeGbRsQoJqahvs6EhgjKuY8xNlE0wfedoAhclBlNzSgx8s2fyJZ/ba7fn71OJGFEGh+xwo9urqbFlsm8T3fLiPAnyfbyirBdqxWauV7bxxJOxnV95PPoyxApX5iOGhgxwu/V/ycY/2G7sAMjLGqUvrE9+ULhj2/0qeN18DaUzz7C6Q2781Smo2++KjeQQZN9ymnFCCOAKCkulJjqDgL5vIAmvdPrtH1vKuRO4GVO6mzfRssn9c8GHK3ZkcrklkA0XBCPjM1qFCmrP6Y5UqaUWIi+d0k6ePHcfFiJGDBNpRgctMvS/7TmjjvnWFv8R6qKBpV2BuBqfJy97JMh6S8ojYi4Ii9UwcdzHRPf8SGFaj/akEf3Y2fF8qkBpqEAAyIeKJiC5sQSVkIsVEkvk9FwsEI532M3AZfLMsui7NMXZys8OFE54IdHP7ydkP+2Es5UUuMWGHqgqobsPIs5ObPOvFGM4zMRMgRfl+imNy69Qgd5pE+6A/FVDcnL0rdFtB76yq19rPtTmygthOgr4MeakuSE7T52f14nlRBjSHKUDwmYM/D8r2cSUzwtgSjDzK3uYRYKU="
  project: "jremillard-blog"
  message: Deploying to Firebase...
