language: ruby
rvm:
  - 2.6.0

before_install:
  - gem update --system
  - gem install bundler
  - gem install html-proofer

cache: bundler

script:
  - bundle check || bundle install
  - set -e
  - bundle exec jekyll build
  - ls _site/

deploy:
  provider: firebase
  token:
    secure: "YtSPPjtZnWGRvJa0dYknUJlhD8QqqiKciEeswvWW9S8KSYkD2F+VHWEW30NfEgka1ICzGaVAMOuA3tQwjBoZaZ0C3sGwUB22snXU1JiAwgRFn7V2z6md9yhP9GV85ylCFjYqDsWAhl6qN4TdFSphHq23DFm0Dm01YuMHXOtzRz9nDZOx2ZiVkUrLZwARPwU0ExrSZ1WWMRApsOs/U4uvtpjUS5jUacQxaO4gbJTVGJ6v1se4J92fDkB7kmPDWJLqlSyBb1z6WoGCS3/6LwxCN5rLzxMJ0zDAw9Ckux/T22DkaRxMK7hUyxZAtESWFye5TBpGgkblAyTLVPS2bnz/h0X1S2wxvrlsCleHK3Wiu24Hd5pnch2ZmTSPOCqDIrCUHz73P3UxIv6FOP9IlTv0sMc0OvX0BItXIm6YAPEV3ax0YQyKVKEghWiH/UbErhnvDVIqQJuiAaKzOBkOGfyiDperqrBJYnOHiVjIbcsPMmloZq21o8hEL1RU3zjItTQxyG+Y5z2aww3Tf9wOa3xFZF4cQvKMEZRjEvHIkDE/VFgnTmS1Er73eBwuJ+0AGu8fFOIDwKYP1UnFuyBGiiRW5H/z0GAnqhLz8AUjcb0sY9MFG9jZW3tBlrbFQ04paZdxtAdAUMLrdI3FyriFCsP198xPdZvIoTYBckVkLVNE+l4="
  skip_cleanup: true
  project: "jremillard-blog"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
